# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=8)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys_apikey',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='api_keys_ap_organiz_79abfa_idx'), models.Index(fields=['key_hash'], name='api_keys_ap_key_has_da7081_idx'), models.Index(fields=['prefix'], name='api_keys_ap_prefix_fda2a7_idx'), models.Index(fields=['is_active'], name='api_keys_ap_is_acti_1dc9d8_idx'), models.Index(fields=['expires_at'], name='api_keys_ap_expires_f049af_idx')],
            },
        ),
    ]
