# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('filebeat', 'Filebeat'), ('fluentd', 'Fluentd'), ('kafka', 'Kafka'), ('api', 'API'), ('github', 'GitHub'), ('pagerduty', 'PagerDuty'), ('confluence', 'Confluence')], default='api', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='projects.project')),
            ],
            options={
                'verbose_name': 'Log Source',
                'verbose_name_plural': 'Log Sources',
                'db_table': 'log_sources_logsource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='log_sources_project_a9c703_idx'), models.Index(fields=['source_type'], name='log_sources_source__842681_idx'), models.Index(fields=['is_active'], name='log_sources_is_acti_e47734_idx')],
            },
        ),
    ]
