# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('web', 'Web Service'), ('database', 'Database'), ('queue', 'Message Queue'), ('cache', 'Cache'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=20)),
                ('repository_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.project')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='services_se_project_db3064_idx'), models.Index(fields=['service_type'], name='services_se_service_9fa833_idx')],
            },
        ),
    ]
