# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('document_source', models.CharField(max_length=1000)),
                ('content_metadata', models.JSONField(blank=True, default=dict)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('graph_indexing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_postmortems', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmortems', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Postmortem',
                'verbose_name_plural': 'Postmortems',
                'db_table': 'postmortems_postmortem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident'], name='postmortems_inciden_389b0d_idx'), models.Index(fields=['ingestion_status'], name='postmortems_ingesti_7c8f9e_idx'), models.Index(fields=['processing_status'], name='postmortems_process_d9a364_idx'), models.Index(fields=['embedding_status'], name='postmortems_embeddi_8ae845_idx'), models.Index(fields=['graph_indexing_status'], name='postmortems_graph_i_7f2e2b_idx'), models.Index(fields=['created_by'], name='postmortems_created_113c80_idx')],
            },
        ),
    ]
