# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations_organization',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('ENGINEER', 'Engineer'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'db_table': 'organizations_membership',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user'], name='organizatio_user_id_8b9547_idx'), models.Index(fields=['organization'], name='organizatio_organiz_aa97be_idx'), models.Index(fields=['role'], name='organizatio_role_af7142_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization')],
            },
        ),
    ]
