# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Medium'), ('P4', 'Low')], default='P3', max_length=2)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('suspected_root_cause', models.TextField(blank=True)),
                ('confirmed_root_cause', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_services', models.ManyToManyField(blank=True, related_name='incidents', to='services.service')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents_incident',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='incidents_i_project_59865b_idx'), models.Index(fields=['severity'], name='incidents_i_severit_10e3a5_idx'), models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'), models.Index(fields=['created_by'], name='incidents_i_created_6b6307_idx'), models.Index(fields=['started_at'], name='incidents_i_started_1aaf3f_idx'), models.Index(fields=['detected_at'], name='incidents_i_detecte_756a5f_idx'), models.Index(fields=['resolved_at'], name='incidents_i_resolve_9d0fd6_idx')],
            },
        ),
    ]
