# Generated by Django 5.1.15 on 2026-08-11 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('viewed', 'Viewed'), ('ingested', 'Ingested'), ('exported', 'Exported')], max_length=20)),
                ('resource_type', models.CharField(choices=[('Incident', 'Incident'), ('Postmortem', 'Postmortem'), ('Project', 'Project'), ('Service', 'Service'), ('Organization', 'Organization'), ('User', 'User'), ('LogSource', 'Log Source'), ('APIKey', 'API Key')], max_length=30)),
                ('resource_id', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='audit_audit_organiz_b2fceb_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['resource_type'], name='audit_audit_resourc_92cef7_idx'), models.Index(fields=['resource_id'], name='audit_audit_resourc_34e0d8_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
